#pragma once

// IWYU pragma: begin_exports
#include "F4SE/Impl/PCH.hpp"

#include "F4SE/API.hpp"
#include "F4SE/ConcreteObjectFactory.hpp"
#include "F4SE/Core.hpp"
#include "F4SE/DelayFunctorManager.hpp"
#include "F4SE/Events.hpp"
#include "F4SE/IDelayFunctor.hpp"
#include "F4SE/IObject.hpp"
#include "F4SE/IObjectFactory.hpp"
#include "F4SE/ITaskDelegate.hpp"
#include "F4SE/Inputs.hpp"
#include "F4SE/LoadInterface.hpp"
#include "F4SE/Menus.hpp"
#include "F4SE/MessagingInterface.hpp"
#include "F4SE/ObjectInterface.hpp"
#include "F4SE/ObjectRegistry.hpp"
#include "F4SE/PapyrusInterface.hpp"
#include "F4SE/PersistentObjectStorage.hpp"
#include "F4SE/PluginInfo.hpp"
#include "F4SE/PluginVersionData.hpp"
#include "F4SE/PreLoadInterface.hpp"
#include "F4SE/QueryInterface.hpp"
#include "F4SE/Runtimes.hpp"
#include "F4SE/ScaleformInterface.hpp"
#include "F4SE/SerializationInterface.hpp"
#include "F4SE/SharedObjectFactory.hpp"
#include "F4SE/TaskDelegate.hpp"
#include "F4SE/TaskInterface.hpp"
#include "F4SE/TrampolineInterface.hpp"
#include "F4SE/Translations.hpp"
#include "F4SE/Versions.hpp"

#include "RE/Game.hpp"
#include "Scaleform/Scaleform.hpp"
#include "msvc/msvc.hpp"
// IWYU pragma: end_exports
