#pragma once

namespace REX::PS4
{
	// NOLINTNEXTLINE(cppcoreguidelines-use-enum-class)
	enum SCE_PAD_BUTTON : std::uint32_t
	{
		SCE_PAD_BUTTON_SHARE = 1 << 0,
		SCE_PAD_BUTTON_L3 = 1 << 1,
		SCE_PAD_BUTTON_R3 = 1 << 2,
		SCE_PAD_BUTTON_OPTIONS = 1 << 3,
		SCE_PAD_BUTTON_UP = 1 << 4,
		SCE_PAD_BUTTON_RIGHT = 1 << 5,
		SCE_PAD_BUTTON_DOWN = 1 << 6,
		SCE_PAD_BUTTON_LEFT = 1 << 7,
		SCE_PAD_BUTTON_L2 = 1 << 8,
		SCE_PAD_BUTTON_R2 = 1 << 9,
		SCE_PAD_BUTTON_L1 = 1 << 10,
		SCE_PAD_BUTTON_R1 = 1 << 11,
		SCE_PAD_BUTTON_TRIANGLE = 1 << 12,
		SCE_PAD_BUTTON_CIRCLE = 1 << 13,
		SCE_PAD_BUTTON_CROSS = 1 << 14,
		SCE_PAD_BUTTON_SQUARE = 1 << 15,
		SCE_PAD_BUTTON_PLAYSTATION = 1 << 16,
		SCE_PAD_BUTTON_TOUCH_PAD = 1 << 20,
		SCE_PAD_BUTTON_INTERCEPTED = 1ui32 << 31
	};
}
